[build]
  command = "bash netlify/install_flutter.sh && flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.24.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

